spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/micromall_ums?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations:
    - classpath*:/mapper/**/*.xml
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
server:
  port: 8000